version: '3.7'

services:
  db:
    image: postgres:11.3-alpine
    container_name: notetaker_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data-postgres:/var/lib/postgres/data
  app:
    build: .
    ports:
      - "4000:4000"
    container_name: notetaker_app
    volumes:
      - ./lib:/app/lib
      - ./assets/css:/app/assets/css
      - ./assets/js:/app/assets/js
      - ./assets/static:/app/assets/static
      - ./assets/vendor:/app/assets/vendor


    environment:
      - MIX_ENV=dev
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=notes_dev
    depends_on:
      - db
volumes:
  data-postgres:
    driver: local
